In [4]:

import numpy as np 



In [6]:
np.ones(shape=3)

array([1., 1., 1.])

In [9]:
np.ones

<function numpy.ones(shape, dtype=None, order='C')>

In [11]:
a= np.ones([2,2])

In [13]:
a

array([[1., 1.],
       [1., 1.]])

In [16]:
a

array([[ 1.,  1.],
       [ 1., 18.]])

In [17]:
a[1, 1]= 18

In [20]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'others': [bool, object, bytes, str, numpy.void]}

In [24]:
a= np.array([1, 100, 110], dtype=np.int8)

In [27]:
a.dtype

dtype('int8')

In [32]:
a.itemsize
a.nbytes

3