In [2]:
import numpy as np 

In [8]:
a= np.random.randint(1, 10, size=(3, 3))

In [10]:
a

array([[5, 1, 8],
       [3, 5, 5],
       [8, 7, 6]])

In [23]:
a[0:3,1:3]

array([[1, 8],
       [5, 5],
       [7, 6]])

In [27]:
b= np.random.randint(1,10, size=(4, 4))
b

array([[8, 5, 2, 4],
       [8, 2, 8, 3],
       [3, 9, 3, 5],
       [7, 5, 3, 4]])

In [29]:
b.reshape(8, 2)

array([[8, 5],
       [2, 4],
       [8, 2],
       [8, 3],
       [3, 9],
       [3, 5],
       [7, 5],
       [3, 4]])

In [40]:
mars= np.random.randint(-5, 25, size=31)
mars

array([19, 19, 14, -3, 14, -3,  6, -3,  3,  7,  3,  5, 13, 19, -1, 20,  6,
       17, 11,  6,  9,  3, 18, 19, 23, 18, -4, 10, -2, 11, -1])

In [41]:
np.sum(mars > 0)

24

In [43]:
np.any(mars == 0)

False

In [49]:
jours_mars= np.arange(1, mars.size +1, dtype= np.int8)

In [51]:
jours_mars

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], dtype=int8)

In [53]:
np.sum((mars > 10) & (jours_mars >12))

10

In [55]:
moy= np.mean((mars[mars > 0]))

In [57]:
mars[mars < 0] = moy

In [61]:
countries = np.array(['fr', 'us', 'jp'])


In [66]:
countries[[0, 0,2, 2, 1, 0, 0]]

array(['fr', 'fr', 'jp', 'jp', 'us', 'fr', 'fr'], dtype='<U2')