In [9]:
import numpy as np

In [6]:
a= np.arange(1000)


In [14]:
%timeit [x**2 +2*x -1 for x in a]

808 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
%timeit a**2 +2*a -1

4.82 µs ± 21.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [46]:
a= np.arange(1,1_000_000, dtype= np.float64)
%timeit -r 1 -n 1 np.sqrt(a)

6.46 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [47]:
%timeit  np.sqrt(a,out=a)
a[5:]

839 µs ± 2.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


array([1., 1., 1., ..., 1., 1., 1.])

In [53]:
#ajouter la fct at 
b= np.log.at (a,[2, 4])
b

In [56]:
a= np.arange(1, 10).reshape(3, 3)

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.sum(a, axis=1)

array([ 6, 15, 24])

In [62]:
np.sum(a, axis=0)

array([12, 15, 18])

In [67]:
c= np.arange(1, 10, dtype=np.float64).reshape(3, 3)
c

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [69]:
c[1, 1]= np.nan

In [71]:
np.mean(c)

nan

In [73]:
np.nanmean(c)

5.0

In [74]:
np.nanmax(c)

9.0